---
title: "Introduction to bigmi: Big Mutual Information"
output: rmarkdown::html_vignette
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: Mikkel Meyer Andersen
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Introduction}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(fig.width = 7, cache = FALSE)
```

## Introduction

First, the library is loaded:
```{r, message=FALSE}
library(bigmi)
```


```{r}
data(danedb)
db <- danedb
db[, "DYS389II"] <- db[, "DYS389II"] - db[, "DYS389I"]
```


```{r}
MI_categorical_all_pairwise(db)
```

```{r}
res <- MI_categorical_worker_sparse_all(db, TRUE); head(res$mi); head(res$idx)

entropy::mi.plugin(prop.table(table(db[, 6], danedb[, 11])), unit = "log")
entropy::mi.plugin(prop.table(table(db[, 11], danedb[, 12])), unit = "log")
```


```{r}
load("~/Desktop/rpartSqrtdat.RData")
d <- d1[, -(1:2)]
colnames(d)
dim(d)

# res <- MI_categorical_worker_sparse_all(d, TRUE)
# head(res$mi)
# head(res$idx)

#dmat <- as.matrix(d)[, 1:100]
dmat <- as.matrix(d)
res <- pearson_correlation_absolute_sparse_all(dmat, TRUE)
str(res, 1)

head(res$corr)
head(res$idx)

cor(dmat[, res$idx[1, 1]], dmat[, res$idx[1, 2]])
res$corr[1]

for (i in 1:10) {
  c1 <- cor(dmat[, res$idx[i, 1]], dmat[, res$idx[i, 2]])
  c2 <- res$corr[i]
  print(all.equal(c1, c2))
}

head(res$corr)
i <- which(res$corr < 0)[1]
i
c1 <- cor(dmat[, res$idx[i, 1]], dmat[, res$idx[i, 2]])
c2 <- res$corr[i]
c1
c2
print(all.equal(c1, c2))


# head(res$mi)
# head(res$idx)
```

```{r}
library(bigmi)

load("~/Desktop/rpartSqrtdat.RData")
d <- d1[, -(1:2)]
dmat <- as.matrix(d)
res <- pearson_correlation_absolute_sparse_all(dmat, TRUE)

graph_has_cycle <- function(graph) {
  if (!methods::is(graph, "igraph")) {
    stop("graph must be igraph")
  }
  
  n <- length(igraph::V(graph))
  L <- igraph::laplacian_matrix(graph, sparse = TRUE)
  rknL <- Matrix::rankMatrix(L, method = "qr.R") # sparse
  trL <- sum(Matrix::diag(L))
  
  if (0.5*trL >= rknL+1) {
    return(TRUE)
  }
  
  return(FALSE)
}

g_final <- igraph::make_empty_graph(directed = FALSE) + 
  igraph::vertices(colnames(dmat))

for (i in seq_len(nrow(res$idx))) {
  #i <- 1
  pair <- res$idx[i, ]
  pair_nm <- colnames(dmat)[pair]
  
  g_new <- g_final + igraph::edge(pair_nm[1], pair_nm[2])
  
  if (i %% 1000 == 0) {
    cat("i = ", i, "; |E| = ", length(igraph::E(g_final)), "\n", sep = "")
  }
  
  if (graph_has_cycle(g_new)) {
    next
  }
  
  g_final <- g_new
  
  if (length(igraph::E(g_final)) == (ncol(dmat) - 1L)) {
    break
  } 
}

igraph::write_graph(g_final, "~/Desktop/rpartSqrtdat-minspan.el", format = "edgelist")
g_final
```



