# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MI_categorical_worker_two <- function(d) {
    .Call('_bigmi_MI_categorical_worker_two', PACKAGE = 'bigmi', d)
}

MI_categorical_worker_all <- function(d) {
    .Call('_bigmi_MI_categorical_worker_all', PACKAGE = 'bigmi', d)
}

#' Sort mutual information matrix
#' 
#' Sort square matrix with mutual information, e.g. obtained by [MI_categorical_all_pairwise()].
#' 
#' @param d Matrix with observations
#' @return Matrix with two columns with the (row, column) indices
#' 
#' @export
MI_order <- function(d) {
    .Call('_bigmi_MI_order', PACKAGE = 'bigmi', d)
}

