# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MI_categorical_worker_two <- function(d) {
    .Call('_bigmi_MI_categorical_worker_two', PACKAGE = 'bigmi', d)
}

MI_categorical_worker_all <- function(d) {
    .Call('_bigmi_MI_categorical_worker_all', PACKAGE = 'bigmi', d)
}

MI_categorical_worker_sparse_all <- function(d, progress = TRUE) {
    .Call('_bigmi_MI_categorical_worker_sparse_all', PACKAGE = 'bigmi', d, progress)
}

pearson_correlation_sparse_all <- function(d, progress = TRUE) {
    .Call('_bigmi_pearson_correlation_sparse_all', PACKAGE = 'bigmi', d, progress)
}

